POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/4815b103-e213-4d17-89a3-7199b38d435d/attendees
Content-Type: application/json

{
  "name": "Gustavo Campagnin",
  "email": "gcampagnin2@gmail.com"
}

###

GET http://localhost:3333/events/4815b103-e213-4d17-89a3-7199b38d435d

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/4815b103-e213-4d17-89a3-7199b38d435d/attendees?query=gustavo
